//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecat.Dal.BbWs.CourseMember {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="CourseMembership.WSPortType", Namespace="http://coursemembership.ws.blackboard/", ConfigurationName="BbWs.CourseMember.CourseMembershipWSPortType")]
    public interface CourseMembershipWSPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message initializeCourseMembershipWSRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="initializeCourseMembershipWS", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/initializeCourseMembership" +
            "WSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse initializeCourseMembershipWS(Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="initializeCourseMembershipWS", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/initializeCourseMembership" +
            "WSResponse")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse> initializeCourseMembershipWSAsync(Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message saveCourseMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="saveCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/saveCourseMembershipRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse saveCourseMembership(Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="saveCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/saveCourseMembershipRespon" +
            "se")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse> saveCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message getCourseMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getCourseMembershipRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse getCourseMembership(Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getCourseMembershipRespons" +
            "e")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse> getCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message saveGroupMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="saveGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/saveGroupMembershipRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse saveGroupMembership(Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="saveGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/saveGroupMembershipRespons" +
            "e")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse> saveGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message getServerVersionRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getServerVersion", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getServerVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.getServerVersionResponse getServerVersion(Ecat.Dal.BbWs.CourseMember.getServerVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getServerVersion", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getServerVersionResponse")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getServerVersionResponse> getServerVersionAsync(Ecat.Dal.BbWs.CourseMember.getServerVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message deleteCourseMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="deleteCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/deleteCourseMembershipResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse deleteCourseMembership(Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="deleteCourseMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/deleteCourseMembershipResp" +
            "onse")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse> deleteCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message deleteGroupMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="deleteGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/deleteGroupMembershipRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse deleteGroupMembership(Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="deleteGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/deleteGroupMembershipRespo" +
            "nse")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse> deleteGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message getGroupMembershipRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getGroupMembershipResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse getGroupMembership(Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getGroupMembership", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getGroupMembershipResponse" +
            "")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse> getGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://coursemembership.ws.blackboard) of message getCourseRolesRequest does not match the default value (http://coursemembership.ws.blackboard/)
        [System.ServiceModel.OperationContractAttribute(Action="getCourseRoles", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getCourseRolesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse getCourseRoles(Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getCourseRoles", ReplyAction="http://coursemembership.ws.blackboard/CourseMembership/getCourseRolesResponse")]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse> getCourseRolesAsync(Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initializeCourseMembershipWS", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class initializeCourseMembershipWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        public bool ignore;
        
        public initializeCourseMembershipWSRequest() {
        }
        
        public initializeCourseMembershipWSRequest(bool ignore) {
            this.ignore = ignore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initializeCourseMembershipWSResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class initializeCourseMembershipWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        public bool @return;
        
        public initializeCourseMembershipWSResponse() {
        }
        
        public initializeCourseMembershipWSResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class CourseMembershipVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> availableField;
        
        private bool availableFieldSpecified;
        
        private string courseIdField;
        
        private string dataSourceIdField;
        
        private long enrollmentDateField;
        
        private bool enrollmentDateFieldSpecified;
        
        private string[] expansionDataField;
        
        private System.Nullable<bool> hasCartridgeAccessField;
        
        private bool hasCartridgeAccessFieldSpecified;
        
        private string idField;
        
        private string imageFileField;
        
        private string roleIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
                this.RaisePropertyChanged("available");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availableSpecified {
            get {
                return this.availableFieldSpecified;
            }
            set {
                this.availableFieldSpecified = value;
                this.RaisePropertyChanged("availableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string courseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
                this.RaisePropertyChanged("courseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
                this.RaisePropertyChanged("dataSourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long enrollmentDate {
            get {
                return this.enrollmentDateField;
            }
            set {
                this.enrollmentDateField = value;
                this.RaisePropertyChanged("enrollmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enrollmentDateSpecified {
            get {
                return this.enrollmentDateFieldSpecified;
            }
            set {
                this.enrollmentDateFieldSpecified = value;
                this.RaisePropertyChanged("enrollmentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true, Order=4)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
                this.RaisePropertyChanged("expansionData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> hasCartridgeAccess {
            get {
                return this.hasCartridgeAccessField;
            }
            set {
                this.hasCartridgeAccessField = value;
                this.RaisePropertyChanged("hasCartridgeAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasCartridgeAccessSpecified {
            get {
                return this.hasCartridgeAccessFieldSpecified;
            }
            set {
                this.hasCartridgeAccessFieldSpecified = value;
                this.RaisePropertyChanged("hasCartridgeAccessSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string imageFile {
            get {
                return this.imageFileField;
            }
            set {
                this.imageFileField = value;
                this.RaisePropertyChanged("imageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string roleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("roleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class CourseMembershipRoleVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string courseRoleDescriptionField;
        
        private System.Nullable<bool> defaultRoleField;
        
        private bool defaultRoleFieldSpecified;
        
        private string[] expansionDataField;
        
        private string orgRoleDescriptionField;
        
        private string roleIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string courseRoleDescription {
            get {
                return this.courseRoleDescriptionField;
            }
            set {
                this.courseRoleDescriptionField = value;
                this.RaisePropertyChanged("courseRoleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> defaultRole {
            get {
                return this.defaultRoleField;
            }
            set {
                this.defaultRoleField = value;
                this.RaisePropertyChanged("defaultRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultRoleSpecified {
            get {
                return this.defaultRoleFieldSpecified;
            }
            set {
                this.defaultRoleFieldSpecified = value;
                this.RaisePropertyChanged("defaultRoleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true, Order=2)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
                this.RaisePropertyChanged("expansionData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string orgRoleDescription {
            get {
                return this.orgRoleDescriptionField;
            }
            set {
                this.orgRoleDescriptionField = value;
                this.RaisePropertyChanged("orgRoleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string roleIdentifier {
            get {
                return this.roleIdentifierField;
            }
            set {
                this.roleIdentifierField = value;
                this.RaisePropertyChanged("roleIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.platform.blackboard/xsd")]
    public partial class VersionVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
                this.RaisePropertyChanged("versionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class GroupMembershipVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string courseMembershipIdField;
        
        private string[] expansionDataField;
        
        private string groupIdField;
        
        private string groupMembershipIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string courseMembershipId {
            get {
                return this.courseMembershipIdField;
            }
            set {
                this.courseMembershipIdField = value;
                this.RaisePropertyChanged("courseMembershipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true, Order=1)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
                this.RaisePropertyChanged("expansionData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string groupMembershipId {
            get {
                return this.groupMembershipIdField;
            }
            set {
                this.groupMembershipIdField = value;
                this.RaisePropertyChanged("groupMembershipId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coursemembership.ws.blackboard/xsd")]
    public partial class MembershipFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] courseIdsField;
        
        private string[] courseMembershipIdsField;
        
        private string[] expansionDataField;
        
        private int filterTypeField;
        
        private bool filterTypeFieldSpecified;
        
        private string[] groupIdsField;
        
        private string[] groupMembershipIdsField;
        
        private string[] roleIdsField;
        
        private string[] userIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseIds", IsNullable=true, Order=0)]
        public string[] courseIds {
            get {
                return this.courseIdsField;
            }
            set {
                this.courseIdsField = value;
                this.RaisePropertyChanged("courseIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("courseMembershipIds", IsNullable=true, Order=1)]
        public string[] courseMembershipIds {
            get {
                return this.courseMembershipIdsField;
            }
            set {
                this.courseMembershipIdsField = value;
                this.RaisePropertyChanged("courseMembershipIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expansionData", IsNullable=true, Order=2)]
        public string[] expansionData {
            get {
                return this.expansionDataField;
            }
            set {
                this.expansionDataField = value;
                this.RaisePropertyChanged("expansionData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
                this.RaisePropertyChanged("filterType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterTypeSpecified {
            get {
                return this.filterTypeFieldSpecified;
            }
            set {
                this.filterTypeFieldSpecified = value;
                this.RaisePropertyChanged("filterTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupIds", IsNullable=true, Order=4)]
        public string[] groupIds {
            get {
                return this.groupIdsField;
            }
            set {
                this.groupIdsField = value;
                this.RaisePropertyChanged("groupIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupMembershipIds", IsNullable=true, Order=5)]
        public string[] groupMembershipIds {
            get {
                return this.groupMembershipIdsField;
            }
            set {
                this.groupMembershipIdsField = value;
                this.RaisePropertyChanged("groupMembershipIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roleIds", IsNullable=true, Order=6)]
        public string[] roleIds {
            get {
                return this.roleIdsField;
            }
            set {
                this.roleIdsField = value;
                this.RaisePropertyChanged("roleIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userIds", IsNullable=true, Order=7)]
        public string[] userIds {
            get {
                return this.userIdsField;
            }
            set {
                this.userIdsField = value;
                this.RaisePropertyChanged("userIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveCourseMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class saveCourseMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("cmArray", IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] cmArray;
        
        public saveCourseMembershipRequest() {
        }
        
        public saveCourseMembershipRequest(string courseId, Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] cmArray) {
            this.courseId = courseId;
            this.cmArray = cmArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveCourseMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class saveCourseMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public saveCourseMembershipResponse() {
        }
        
        public saveCourseMembershipResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCourseMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getCourseMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.MembershipFilter f;
        
        public getCourseMembershipRequest() {
        }
        
        public getCourseMembershipRequest(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            this.courseId = courseId;
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCourseMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getCourseMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] @return;
        
        public getCourseMembershipResponse() {
        }
        
        public getCourseMembershipResponse(Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveGroupMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class saveGroupMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("g", IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] g;
        
        public saveGroupMembershipRequest() {
        }
        
        public saveGroupMembershipRequest(string courseId, Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] g) {
            this.courseId = courseId;
            this.g = g;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveGroupMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class saveGroupMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public saveGroupMembershipResponse() {
        }
        
        public saveGroupMembershipResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerVersion", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getServerVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.VersionVO unused;
        
        public getServerVersionRequest() {
        }
        
        public getServerVersionRequest(Ecat.Dal.BbWs.CourseMember.VersionVO unused) {
            this.unused = unused;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerVersionResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getServerVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.VersionVO @return;
        
        public getServerVersionResponse() {
        }
        
        public getServerVersionResponse(Ecat.Dal.BbWs.CourseMember.VersionVO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCourseMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class deleteCourseMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)]
        public string[] ids;
        
        public deleteCourseMembershipRequest() {
        }
        
        public deleteCourseMembershipRequest(string courseId, string[] ids) {
            this.courseId = courseId;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCourseMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class deleteCourseMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public deleteCourseMembershipResponse() {
        }
        
        public deleteCourseMembershipResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGroupMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class deleteGroupMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("ids", IsNullable=true)]
        public string[] ids;
        
        public deleteGroupMembershipRequest() {
        }
        
        public deleteGroupMembershipRequest(string courseId, string[] ids) {
            this.courseId = courseId;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteGroupMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class deleteGroupMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public deleteGroupMembershipResponse() {
        }
        
        public deleteGroupMembershipResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupMembership", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getGroupMembershipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string courseId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.MembershipFilter f;
        
        public getGroupMembershipRequest() {
        }
        
        public getGroupMembershipRequest(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            this.courseId = courseId;
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupMembershipResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getGroupMembershipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] @return;
        
        public getGroupMembershipResponse() {
        }
        
        public getGroupMembershipResponse(Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCourseRoles", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getCourseRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("roleIds", Namespace="http://coursemembership.ws.blackboard/xsd")]
        public string[] f;
        
        public getCourseRolesRequest() {
        }
        
        public getCourseRolesRequest(string[] f) {
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCourseRolesResponse", WrapperNamespace="http://coursemembership.ws.blackboard", IsWrapped=true)]
    public partial class getCourseRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coursemembership.ws.blackboard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ecat.Dal.BbWs.CourseMember.CourseMembershipRoleVO[] @return;
        
        public getCourseRolesResponse() {
        }
        
        public getCourseRolesResponse(Ecat.Dal.BbWs.CourseMember.CourseMembershipRoleVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourseMembershipWSPortTypeChannel : Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseMembershipWSPortTypeClient : System.ServiceModel.ClientBase<Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType>, Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType {
        
        public CourseMembershipWSPortTypeClient() {
        }
        
        public CourseMembershipWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseMembershipWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMembershipWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseMembershipWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.initializeCourseMembershipWS(Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest request) {
            return base.Channel.initializeCourseMembershipWS(request);
        }
        
        public bool initializeCourseMembershipWS(bool ignore) {
            Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest inValue = new Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest();
            inValue.ignore = ignore;
            Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).initializeCourseMembershipWS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.initializeCourseMembershipWSAsync(Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest request) {
            return base.Channel.initializeCourseMembershipWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSResponse> initializeCourseMembershipWSAsync(bool ignore) {
            Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest inValue = new Ecat.Dal.BbWs.CourseMember.initializeCourseMembershipWSRequest();
            inValue.ignore = ignore;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).initializeCourseMembershipWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.saveCourseMembership(Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest request) {
            return base.Channel.saveCourseMembership(request);
        }
        
        public string[] saveCourseMembership(string courseId, Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] cmArray) {
            Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.cmArray = cmArray;
            Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).saveCourseMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.saveCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest request) {
            return base.Channel.saveCourseMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveCourseMembershipResponse> saveCourseMembershipAsync(string courseId, Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] cmArray) {
            Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.saveCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.cmArray = cmArray;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).saveCourseMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getCourseMembership(Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest request) {
            return base.Channel.getCourseMembership(request);
        }
        
        public Ecat.Dal.BbWs.CourseMember.CourseMembershipVO[] getCourseMembership(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.f = f;
            Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getCourseMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest request) {
            return base.Channel.getCourseMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseMembershipResponse> getCourseMembershipAsync(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.getCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.f = f;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getCourseMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.saveGroupMembership(Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest request) {
            return base.Channel.saveGroupMembership(request);
        }
        
        public string[] saveGroupMembership(string courseId, Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] g) {
            Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.g = g;
            Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).saveGroupMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.saveGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest request) {
            return base.Channel.saveGroupMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.saveGroupMembershipResponse> saveGroupMembershipAsync(string courseId, Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] g) {
            Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.saveGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.g = g;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).saveGroupMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.getServerVersionResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getServerVersion(Ecat.Dal.BbWs.CourseMember.getServerVersionRequest request) {
            return base.Channel.getServerVersion(request);
        }
        
        public Ecat.Dal.BbWs.CourseMember.VersionVO getServerVersion(Ecat.Dal.BbWs.CourseMember.VersionVO unused) {
            Ecat.Dal.BbWs.CourseMember.getServerVersionRequest inValue = new Ecat.Dal.BbWs.CourseMember.getServerVersionRequest();
            inValue.unused = unused;
            Ecat.Dal.BbWs.CourseMember.getServerVersionResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getServerVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getServerVersionResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getServerVersionAsync(Ecat.Dal.BbWs.CourseMember.getServerVersionRequest request) {
            return base.Channel.getServerVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getServerVersionResponse> getServerVersionAsync(Ecat.Dal.BbWs.CourseMember.VersionVO unused) {
            Ecat.Dal.BbWs.CourseMember.getServerVersionRequest inValue = new Ecat.Dal.BbWs.CourseMember.getServerVersionRequest();
            inValue.unused = unused;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getServerVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.deleteCourseMembership(Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest request) {
            return base.Channel.deleteCourseMembership(request);
        }
        
        public string[] deleteCourseMembership(string courseId, string[] ids) {
            Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.ids = ids;
            Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).deleteCourseMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.deleteCourseMembershipAsync(Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest request) {
            return base.Channel.deleteCourseMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipResponse> deleteCourseMembershipAsync(string courseId, string[] ids) {
            Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.deleteCourseMembershipRequest();
            inValue.courseId = courseId;
            inValue.ids = ids;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).deleteCourseMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.deleteGroupMembership(Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest request) {
            return base.Channel.deleteGroupMembership(request);
        }
        
        public string[] deleteGroupMembership(string courseId, string[] ids) {
            Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.ids = ids;
            Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).deleteGroupMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.deleteGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest request) {
            return base.Channel.deleteGroupMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipResponse> deleteGroupMembershipAsync(string courseId, string[] ids) {
            Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.deleteGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.ids = ids;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).deleteGroupMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getGroupMembership(Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest request) {
            return base.Channel.getGroupMembership(request);
        }
        
        public Ecat.Dal.BbWs.CourseMember.GroupMembershipVO[] getGroupMembership(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.f = f;
            Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getGroupMembership(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getGroupMembershipAsync(Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest request) {
            return base.Channel.getGroupMembershipAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getGroupMembershipResponse> getGroupMembershipAsync(string courseId, Ecat.Dal.BbWs.CourseMember.MembershipFilter f) {
            Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest inValue = new Ecat.Dal.BbWs.CourseMember.getGroupMembershipRequest();
            inValue.courseId = courseId;
            inValue.f = f;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getGroupMembershipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getCourseRoles(Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest request) {
            return base.Channel.getCourseRoles(request);
        }
        
        public Ecat.Dal.BbWs.CourseMember.CourseMembershipRoleVO[] getCourseRoles(string[] f) {
            Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest inValue = new Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest();
            inValue.f = f;
            Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse retVal = ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getCourseRoles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse> Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType.getCourseRolesAsync(Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest request) {
            return base.Channel.getCourseRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ecat.Dal.BbWs.CourseMember.getCourseRolesResponse> getCourseRolesAsync(string[] f) {
            Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest inValue = new Ecat.Dal.BbWs.CourseMember.getCourseRolesRequest();
            inValue.f = f;
            return ((Ecat.Dal.BbWs.CourseMember.CourseMembershipWSPortType)(this)).getCourseRolesAsync(inValue);
        }
    }
}
